on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{secrets.TOKEN}}
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: DeterminateSystems/flake-checker-action@v12
      - run: |
          PORT=$(((RANDOM % 10000) + 20000))
          echo "port=$PORT" >> $GITHUB_OUTPUT
          nix develop --command bash -c "ci-prepare.sh ${PORT}"
          nix develop --command bash -c prisma migrate dev

  cleanup:
    needs: [build]
    runs-on: self-hosted
    steps:
      - run: |
          PORT=${{needs.build-and-check.outputs.port}}
          nix develop --command bash -c "ci-post.sh ${PORT}"
